OPEN = "OPEN"
PENDING_PAYMENT = "PENDING_PAYMENT"
PENDING_SHIPPING = "PENDING_SHIPPING"
SHIPPED = "SHIPPED"
DELIVERED = "DELIVERED"
ORDER_STATUS = (
    (OPEN, OPEN),
    (PENDING_PAYMENT, PENDING_PAYMENT),
    (PENDING_SHIPPING, PENDING_SHIPPING),
    (SHIPPED, SHIPPED),
    (DELIVERED, DELIVERED)
)
